// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSure.PolicyService.Data;

#nullable disable

namespace SmartSure.PolicyService.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260409055905_PolicySchemaAlignment")]
    partial class PolicySchemaAlignment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSure.PolicyService.Models.HomeDetail", b =>
                {
                    b.Property<Guid>("HomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("ConstructionType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("HomeId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("HomeDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceSubType", b =>
                {
                    b.Property<int>("SubTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubTypeId"));

                    b.Property<decimal>("BasePremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SubTypeName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("SubTypeId");

                    b.HasIndex("TypeId", "SubTypeName")
                        .IsUnique();

                    b.ToTable("InsuranceSubTypes");

                    b.HasData(
                        new
                        {
                            SubTypeId = 101,
                            BasePremium = 15000m,
                            SubTypeName = "Mahindra",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 102,
                            BasePremium = 12000m,
                            SubTypeName = "Maruti Suzuki",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 103,
                            BasePremium = 13000m,
                            SubTypeName = "Hyundai",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 104,
                            BasePremium = 14000m,
                            SubTypeName = "Honda",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 105,
                            BasePremium = 13500m,
                            SubTypeName = "Tata Motors",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 106,
                            BasePremium = 16000m,
                            SubTypeName = "Toyota",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 107,
                            BasePremium = 14500m,
                            SubTypeName = "Kia",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 108,
                            BasePremium = 17000m,
                            SubTypeName = "Volkswagen",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 109,
                            BasePremium = 16500m,
                            SubTypeName = "Skoda",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 110,
                            BasePremium = 13000m,
                            SubTypeName = "Renault",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 111,
                            BasePremium = 14000m,
                            SubTypeName = "Nissan",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 112,
                            BasePremium = 15500m,
                            SubTypeName = "Ford",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 113,
                            BasePremium = 15000m,
                            SubTypeName = "MG Motor",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 114,
                            BasePremium = 18000m,
                            SubTypeName = "Jeep",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 115,
                            BasePremium = 25000m,
                            SubTypeName = "BMW",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 116,
                            BasePremium = 28000m,
                            SubTypeName = "Mercedes-Benz",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 117,
                            BasePremium = 26000m,
                            SubTypeName = "Audi",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 118,
                            BasePremium = 24000m,
                            SubTypeName = "Volvo",
                            TypeId = 1
                        },
                        new
                        {
                            SubTypeId = 201,
                            BasePremium = 8000m,
                            SubTypeName = "Apartment",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 202,
                            BasePremium = 12000m,
                            SubTypeName = "Independent House",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 203,
                            BasePremium = 18000m,
                            SubTypeName = "Villa",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 204,
                            BasePremium = 15000m,
                            SubTypeName = "Bungalow",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 205,
                            BasePremium = 20000m,
                            SubTypeName = "Penthouse",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 206,
                            BasePremium = 6000m,
                            SubTypeName = "Studio Apartment",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 207,
                            BasePremium = 14000m,
                            SubTypeName = "Duplex",
                            TypeId = 2
                        },
                        new
                        {
                            SubTypeId = 208,
                            BasePremium = 16000m,
                            SubTypeName = "Farmhouse",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.HasIndex("TypeName")
                        .IsUnique();

                    b.ToTable("InsuranceTypes");

                    b.HasData(
                        new
                        {
                            TypeId = 1,
                            TypeName = "Vehicle"
                        },
                        new
                        {
                            TypeId = 2,
                            TypeName = "Home"
                        });
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TransactionRef")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(14,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InsuranceDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MonthlyPremium")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("SubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyId");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SubTypeId");

                    b.HasIndex("TypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.PolicyDetail", b =>
                {
                    b.Property<Guid>("PolicyDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyDetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("PolicyDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Premium", b =>
                {
                    b.Property<Guid>("PremiumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("PremiumId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Premiums");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.VehicleDetail", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<int?>("EngineCC")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("YearOfMake")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.HomeDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("HomeDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.HomeDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceSubType", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.InsuranceType", "Type")
                        .WithMany("SubTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Payment", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.InsuranceSubType", "SubType")
                        .WithMany("Policies")
                        .HasForeignKey("SubTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartSure.PolicyService.Models.InsuranceType", "Type")
                        .WithMany("Policies")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SubType");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.PolicyDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("PolicyDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.PolicyDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Premium", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithMany("Premiums")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.VehicleDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("VehicleDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.VehicleDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceSubType", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceType", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("SubTypes");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.Navigation("HomeDetail");

                    b.Navigation("Payments");

                    b.Navigation("PolicyDetail");

                    b.Navigation("Premiums");

                    b.Navigation("VehicleDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
